export type Deal = {
  id: string;
  name: string;
  city: string;
  category: "Warehousing" | "Commercial" | "Residential" | "Plotted" | "Industrial" | "Mixed Use";
  investment?: string;
  exitIRR?: string;
  status: "completed" | "current";
  landArea?: string;
  developmentArea?: string;
  /** Full institutional-format case study, Thesis, Structure, Execution, Exit, Outcome. */
  caseStudy?: DealCaseStudy;
};

export type DealCaseStudy = {
  vintage?: string;
  holdPeriod?: string;
  partner?: string;
  thesis: string;
  structure: string;
  execution: string;
  exit: string;
  outcome: string;
};

export const completedDeals: Deal[] = [
  {
    id: "sai-krishna",
    name: "Sai Krishna Warehouse",
    city: "Mumbai",
    category: "Warehousing",
    investment: "INR 45 Crores",
    exitIRR: "23%",
    status: "completed",
    caseStudy: {
      vintage: "2015",
      holdPeriod: "3.5 years",
      partner: "Family-office co-investment",
      thesis:
        "Grade\u2011A warehousing supply in the Bhiwandi\u2013Kalyan corridor lagged the demand generated by 3PL and e-commerce fulfilment. Well-located land with clean title, ready approvals and rail connectivity offered attractive risk-adjusted entry.",
      structure:
        "Deal-level SPV with senior-secured debt and mezzanine tranche. Landmark led underwriting; investors retained deal-level visibility on quarterly cost, lease-up and cash-flow metrics.",
      execution:
        "Aggregation of contiguous parcels, land conversion and Grade\u2011A specification build\u2011out to a leading 3PL tenant. Rent commencement occurred within one quarter of practical completion.",
      exit:
        "Strategic sale to an institutional logistics REIT platform once the asset achieved full stabilisation and the first rent escalation cycle.",
      outcome:
        "23% gross IRR to investors, 1.85x MoIC. Exit priced at a compressed cap rate reflecting the tenant covenant and lease structure.",
    },
  },
  {
    id: "247-park",
    name: "247 Park",
    city: "Mumbai",
    category: "Commercial",
    investment: "INR 775 Crores",
    exitIRR: "21%",
    status: "completed",
    caseStudy: {
      vintage: "2014",
      holdPeriod: "5 years",
      partner: "Joint development with sponsor",
      thesis:
        "Grade\u2011A commercial supply in the Vikhroli\u2013Kanjurmarg belt was constrained despite persistent occupier demand from IT and BFSI. Institutional-grade product with strong specification would command rental premium and cap-rate compression.",
      structure:
        "Structured equity into a project-level SPV alongside the sponsor, with defined governance rights, milestone-linked drawdowns and pre-agreed exit waterfall.",
      execution:
        "Active involvement across leasing strategy, tenant-mix curation and asset management. Achieved anchor lease-up ahead of schedule with weighted-average lease tenor above underwriting.",
      exit:
        "Secondary sale to an institutional buyer at stabilisation, ahead of the fund\u2019s target hold period.",
      outcome:
        "21% gross IRR, 2.3x MoIC. Reference outcome for subsequent institutional co-investments in the Mumbai commercial market.",
    },
  },
  {
    id: "godrej-prakriti",
    name: "Godrej Prakriti",
    city: "Kolkata",
    category: "Residential",
    investment: "INR 85 Crores",
    exitIRR: "22%",
    status: "completed",
    caseStudy: {
      vintage: "2015",
      holdPeriod: "4 years",
      partner: "Grade\u2011A developer partnership",
      thesis:
        "Under-served mid-premium residential segment in emerging North Kolkata micro-markets, with a Grade\u2011A developer partner and clear execution track record.",
      structure:
        "Structured senior participation with priority distribution and defined sales-velocity covenants. Regular deal-level reporting to investors.",
      execution:
        "Phased launch and sales strategy aligned to market absorption. Full compliance with RERA registration and construction milestones.",
      exit:
        "Full principal recovery and priority return distribution at project completion, ahead of contracted timeline.",
      outcome:
        "22% gross IRR, principal-protected structure honoured throughout the hold.",
    },
  },
  {
    id: "acorn-warehouse",
    name: "Acorn Warehouse",
    city: "NCR",
    category: "Warehousing",
    investment: "INR 68 Crores",
    exitIRR: "16%",
    status: "completed",
  },
  {
    id: "ecity",
    name: "E-City",
    city: "Bengaluru",
    category: "Commercial",
    investment: "INR 120 Crores",
    exitIRR: "18%",
    status: "completed",
  },
  {
    id: "ackruti-city",
    name: "Ackruti City",
    city: "Mumbai",
    category: "Residential",
    investment: "INR 60 Crores",
    exitIRR: "21%",
    status: "completed",
  },
];

export const currentDeals: Deal[] = [
  {
    id: "doddaballapur",
    name: "Plotted Development",
    city: "Bengaluru, Doddaballapur",
    category: "Plotted",
    landArea: "22 acres",
    developmentArea: "5 Lakh sq. ft.",
    status: "current",
  },
  {
    id: "sadahalli",
    name: "Villa Development",
    city: "Bengaluru, Sadahalli",
    category: "Residential",
    landArea: "36 acres",
    developmentArea: "14 Lakh sq. ft.",
    status: "current",
  },
  {
    id: "mankoli",
    name: "Industrial Park",
    city: "Mumbai, Mankoli",
    category: "Industrial",
    landArea: "16.5 acres",
    developmentArea: "17 Lakh sq. ft.",
    status: "current",
  },
  {
    id: "dhamanagaon",
    name: "Warehousing",
    city: "Mumbai, Dhamanagaon",
    category: "Warehousing",
    landArea: "55 acres",
    developmentArea: "15 Lakh sq. ft.",
    status: "current",
  },
  {
    id: "gachibowli",
    name: "Mixed Use",
    city: "Hyderabad, Gachibowli",
    category: "Mixed Use",
    landArea: "4.4 acres",
    developmentArea: "11 Lakh sq. ft.",
    status: "current",
  },
  {
    id: "manikonda",
    name: "Mixed Use",
    city: "Hyderabad, Manikonda",
    category: "Mixed Use",
    landArea: "8 acres",
    developmentArea: "13 Lakh sq. ft.",
    status: "current",
  },
];
